//! X11 backend: shells out to `xrandr`. Shelling out (rather than binding XCB
//! RandR directly) keeps the code simple, easy to debug, and lets us export
//! the exact command as a reusable shell script.

use std::process::Command;

use anyhow::{anyhow, bail, Context, Result};

use super::DisplayBackend;
use crate::model::{Layout, Mode, Output, OutputConfig, Position, Resolution, Rotation};

pub struct XrandrBackend;

impl XrandrBackend {
    pub fn new() -> Self {
        XrandrBackend
    }
}

impl DisplayBackend for XrandrBackend {
    fn query(&self) -> Result<Vec<Output>> {
        let out = Command::new("xrandr")
            .arg("--query")
            .output()
            .context("failed to run `xrandr --query` (is xrandr installed?)")?;
        if !out.status.success() {
            bail!(
                "xrandr --query failed: {}",
                String::from_utf8_lossy(&out.stderr)
            );
        }
        let text = String::from_utf8_lossy(&out.stdout);
        Ok(parse_query(&text))
    }

    fn apply(&self, layout: &Layout) -> Result<()> {
        let args = build_args(layout);
        if args.is_empty() {
            bail!("refusing to apply an empty layout");
        }
        let out = Command::new("xrandr")
            .args(&args)
            .output()
            .context("failed to run xrandr")?;
        if !out.status.success() {
            return Err(anyhow!(
                "xrandr failed: {}",
                String::from_utf8_lossy(&out.stderr).trim()
            ));
        }
        Ok(())
    }

    fn export_script(&self, layout: &Layout) -> String {
        let args = build_args(layout);
        let mut script = String::from(
            "#!/bin/sh\n# Generated by Display Arranger\n# Re-apply this monitor layout.\n\nxrandr",
        );
        // Group args so each `--output ...` block sits on its own line.
        for arg in &args {
            if arg == "--output" {
                script.push_str(" \\\n  ");
            } else {
                script.push(' ');
            }
            script.push_str(arg);
        }
        script.push('\n');
        script
    }

    fn name(&self) -> &'static str {
        "xrandr"
    }
}

/// Build the `xrandr` argument vector for a layout. Disabled outputs (including
/// disconnected "ghost" outputs that still hold a stale mode) get `--off`,
/// which is exactly what prevents the `xrandr: cannot find mode None` error.
fn build_args(layout: &Layout) -> Vec<String> {
    let mut args: Vec<String> = Vec::new();
    for o in &layout.outputs {
        args.push("--output".into());
        args.push(o.name.clone());

        match (&o.enabled, &o.mode) {
            (true, Some(mode)) => {
                args.push("--mode".into());
                args.push(format!("{}x{}", mode.width, mode.height));
                if let Some(rate) = o.rate {
                    args.push("--rate".into());
                    args.push(format!("{rate:.2}"));
                }
                args.push("--pos".into());
                args.push(format!("{}x{}", o.position.x, o.position.y));
                args.push("--rotate".into());
                args.push(o.rotation.as_xrandr().into());
                if let Some(scale) = o.scale {
                    args.push("--scale".into());
                    args.push(format!("{scale}x{scale}"));
                }
                if o.primary {
                    args.push("--primary".into());
                }
            }
            // Enabled but no resolution, or explicitly disabled -> turn it off.
            _ => {
                args.push("--off".into());
            }
        }
    }
    args
}

/// Parse the output of `xrandr --query` into a list of outputs.
pub fn parse_query(text: &str) -> Vec<Output> {
    let mut outputs: Vec<Output> = Vec::new();

    for line in text.lines() {
        if line.is_empty() {
            continue;
        }
        let indented = line.starts_with(char::is_whitespace);

        if !indented {
            // Possible output header line.
            if line.starts_with("Screen ") {
                continue;
            }
            if let Some(output) = parse_header(line) {
                outputs.push(output);
            }
        } else if let Some(current) = outputs.last_mut() {
            parse_mode_line(line, current);
        }
    }

    outputs
}

fn parse_header(line: &str) -> Option<Output> {
    let tokens: Vec<&str> = line.split_whitespace().collect();
    if tokens.len() < 2 {
        return None;
    }
    let connected = match tokens[1] {
        "connected" => true,
        "disconnected" => false,
        _ => return None, // not an output header
    };

    let name = tokens[0].to_string();
    let primary = tokens.contains(&"primary");

    let mut position = Position::default();
    let mut current_mode = None;
    let mut enabled = false;
    let mut rotation = Rotation::Normal;
    let mut mm_width = 0;
    let mut mm_height = 0;

    for (i, tok) in tokens.iter().enumerate() {
        // Geometry token like "1920x1080+0+0".
        if current_mode.is_none() {
            if let Some((res, pos)) = parse_geometry(tok) {
                current_mode = Some(res);
                position = pos;
                enabled = true;
                // The current rotation, if any, is the token right after geometry.
                if let Some(next) = tokens.get(i + 1) {
                    if let Some(r) = Rotation::parse(next) {
                        rotation = r;
                    }
                }
            }
        }
        // Physical size like "344mm".
        if let Some(stripped) = tok.strip_suffix("mm") {
            if let Ok(v) = stripped.parse::<u32>() {
                if mm_width == 0 {
                    mm_width = v;
                } else {
                    mm_height = v;
                }
            }
        }
    }

    Some(Output {
        name,
        connected,
        primary,
        enabled,
        position,
        current_mode,
        rotation,
        modes: Vec::new(),
        mm_width,
        mm_height,
    })
}

/// Parse a geometry token "WxH+X+Y" into a resolution and position.
fn parse_geometry(tok: &str) -> Option<(Resolution, Position)> {
    if !tok.contains('x') || !tok.contains('+') {
        return None;
    }
    // Split off the two "+N" suffixes from the right.
    let mut parts = tok.splitn(3, '+');
    let res = parts.next()?;
    let x = parts.next()?.parse::<i32>().ok()?;
    let y = parts.next()?.parse::<i32>().ok()?;
    let (w, h) = res.split_once('x')?;
    let width = w.parse::<u32>().ok()?;
    let height = h.parse::<u32>().ok()?;
    Some((Resolution { width, height }, Position { x, y }))
}

/// Parse an indented mode line, appending modes to `output`.
/// Example: "   1920x1080    165.00*+  60.00 +  59.97" — markers `*` (current)
/// and `+` (preferred) may be attached to a rate or stand alone.
fn parse_mode_line(line: &str, output: &mut Output) {
    let mut tokens = line.split_whitespace();
    let Some(res_tok) = tokens.next() else {
        return;
    };
    // Resolution, possibly with an "i" (interlaced) suffix.
    let res = res_tok.trim_end_matches(|c: char| !c.is_ascii_digit() && c != 'x');
    let Some((w, h)) = res.split_once('x') else {
        return;
    };
    let (Ok(width), Ok(height)) = (w.parse::<u32>(), h.parse::<u32>()) else {
        return;
    };

    for tok in tokens {
        let mut current = false;
        let mut preferred = false;
        let mut t = tok;
        while let Some(last) = t.chars().last() {
            match last {
                '*' => current = true,
                '+' => preferred = true,
                _ => break,
            }
            t = &t[..t.len() - last.len_utf8()];
        }

        if t.is_empty() {
            // Standalone marker applies to the most recent mode.
            if let Some(m) = output.modes.last_mut() {
                m.current |= current;
                m.preferred |= preferred;
            }
        } else if let Ok(rate) = t.parse::<f64>() {
            output.modes.push(Mode {
                width,
                height,
                rate,
                current,
                preferred,
            });
        }
    }
}

#[allow(dead_code)]
fn config_for(name: &str) -> OutputConfig {
    OutputConfig {
        name: name.into(),
        enabled: false,
        primary: false,
        position: Position::default(),
        mode: None,
        rate: None,
        rotation: Rotation::Normal,
        scale: None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "\
Screen 0: minimum 320 x 200, current 3840 x 1080, maximum 16384 x 16384
eDP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1920x1080    165.00*+  60.00 +  59.97    59.96    59.93
   1680x1050     59.95    59.88
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-1 connected (normal left inverted right x axis y axis)
   1920x1080     60.00 +
HDMI-1-0 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 598mm x 336mm
   1920x1080     60.00*+ 100.00    74.97    59.94    50.00
";

    #[test]
    fn parses_outputs_and_state() {
        let outs = parse_query(SAMPLE);
        assert_eq!(outs.len(), 4);

        let edp = &outs[0];
        assert_eq!(edp.name, "eDP-1");
        assert!(edp.connected && edp.primary && edp.enabled);
        assert_eq!(edp.position, Position { x: 0, y: 0 });
        assert_eq!(
            edp.current_mode,
            Some(Resolution {
                width: 1920,
                height: 1080
            })
        );
        assert_eq!(edp.mm_width, 344);
        assert_eq!(edp.mm_height, 194);

        // Disconnected ghost: not connected, not enabled.
        let hdmi1 = &outs[1];
        assert_eq!(hdmi1.name, "HDMI-1");
        assert!(!hdmi1.connected && !hdmi1.enabled);

        // Connected but no geometry -> enabled is false.
        let dp1 = &outs[2];
        assert_eq!(dp1.name, "DP-1");
        assert!(dp1.connected && !dp1.enabled);

        let hdmi = &outs[3];
        assert_eq!(hdmi.name, "HDMI-1-0");
        assert_eq!(hdmi.position, Position { x: 1920, y: 0 });
    }

    #[test]
    fn parses_rate_markers() {
        let outs = parse_query(SAMPLE);
        let edp = &outs[0];
        // First resolution should expose 5 rates.
        let r1080: Vec<&Mode> = edp.modes.iter().filter(|m| m.height == 1080).collect();
        assert_eq!(r1080.len(), 5);
        // 165.00 is current + preferred; 60.00 is preferred (standalone +).
        let cur = edp.modes.iter().find(|m| m.current).unwrap();
        assert!((cur.rate - 165.00).abs() < 0.01);
        assert!(cur.preferred);
        let m60 = edp
            .modes
            .iter()
            .find(|m| (m.rate - 60.00).abs() < 0.01)
            .unwrap();
        assert!(m60.preferred && !m60.current);
    }

    #[test]
    fn build_args_turns_off_disabled_and_ghosts() {
        let layout = Layout {
            outputs: vec![
                OutputConfig {
                    name: "eDP-1".into(),
                    enabled: true,
                    primary: true,
                    position: Position { x: 0, y: 0 },
                    mode: Some(Resolution {
                        width: 1920,
                        height: 1080,
                    }),
                    rate: Some(165.0),
                    rotation: Rotation::Normal,
                    scale: None,
                },
                // ghost / disconnected -> must be turned off
                config_for("DP-1"),
            ],
        };
        let args = build_args(&layout);
        let joined = args.join(" ");
        assert!(joined.contains(
            "--output eDP-1 --mode 1920x1080 --rate 165.00 --pos 0x0 --rotate normal --primary"
        ));
        assert!(joined.contains("--output DP-1 --off"));
    }

    #[test]
    fn export_script_has_shebang_and_blocks() {
        let layout = Layout {
            outputs: vec![config_for("DP-1")],
        };
        let backend = XrandrBackend::new();
        let script = backend.export_script(&layout);
        assert!(script.starts_with("#!/bin/sh"));
        assert!(script.contains("xrandr \\\n  --output DP-1 --off"));
    }
}
